config/routes.rb
Rails.application.routes.draw do
  get 'login/index'
  devise_for :attendees
  devise_for :admins
  resources :reviews
  resources :event_tickets
  resources :events do
    get 'available_rooms', on: :collection
  end
  resources :rooms
  resources :attendees
  resources :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "login#index"

  get 'attendees/:id/view_booked_events' => 'attendees#booked_events', :as => :booked_events

  # Route for admin to search for attendees by event name. This maps a GET request to the search_attendees action in the AdminsController.
  get 'admin/search_attendees', to: 'admins#search_attendees', as: 'search_attendees'

  get 'admins/:id/order_history', to: 'admins#order_history', as: 'admin_order_history'
  get 'attendees/:id/order_history', to: 'attendees#order_history', as: 'attendee_order_history'

  # post 'events/available_rooms', to: 'events#available_rooms', as: 'available_rooms'

end

app/views/admins/_admin.html.erb
<div id="<%= dom_id admin %>">
  <p>
    <strong>Admin id:</strong>
    <%= admin.id %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= admin.email %>
  </p>

<!--  <p>-->
<!--    <strong>Password:</strong>-->
    <%#= admin.password %>
<!--  </p>-->

  <p>
    <strong>Name:</strong>
    <%= admin.name %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= admin.phone_number %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= admin.address %>
  </p>

  <p>
    <strong>Credit card info:</strong>
    <%= admin.credit_card_info %>
  </p>

</div>

app/views/admins/_form.html.erb
<%= form_with(model: admin) do |form| %>
  <% if admin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :id, style: "display: block"%>
    <%= form.text_field :id, class: "uneditable-input", :disabled => admin.persisted? %>
  </div>

  <div>
    <%= form.label :email, style: "display: block"%>
    <%= form.text_field :email, class: "uneditable-input", :disabled => admin.persisted? %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password, class: "uneditable-input", :disabled => admin.persisted? %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_area :address %>
  </div>

  <div>
    <%= form.label :credit_card_info, style: "display: block" %>
    <%= form.text_field :credit_card_info %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<!-- app/views/admins/edit.html.erb -->
<h1>Edit Profile</h1>

<!-- Form for editing admin profile, submits to update action with PATCH method-->
<%= form_for(@admin, url: admin_path(@admin), method: :patch) do |f| %>
  <div class="field">
<!--     Label for admin name field-->
    <%= f.label :name %>
<!--    Text field for updating admin name-->
    <%= f.text_field :name %>
  </div>

  <div class="field">
<!--Label for admin phone number field-->
    <%= f.label :phone_number %>
<!--     Text field for updating admin phone number-->
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
<!--Label for admin address field-->
    <%= f.label :address %>
<!--    Text field to update admin address-->
    <%= f.text_field :address %>
  </div>

  <div class="field">
<!--Label for admin credit card info field-->
    <%= f.label :credit_card_info %>
<!--    Text field for updating admin credit card info-->
    <%= f.text_field :credit_card_info %>
  </div>

  <div class="actions">
<!--    Submit button to update admin profile-->
    <%= f.submit "Update Profile" %>
  </div>
<% end %>

<!-- Link to return to admin homepage-->
<%= link_to "Return to Homepage", admin_homepage_path %>

app/views/admins/home.html.erb
<h1>Admin Homepage</h1>
<p>See administrator options below:</p>

<!--Edit Profile-->
<%= link_to "Edit Profile", edit_profile_admins_path %>
<p>
<!-- Events Button -->
<%= link_to "Events List", events_path %>
<p>
<!-- Rooms Button -->
<%= link_to "Rooms", rooms_path %>
<p>
Reviews
<p>
  <%= link_to "manage attendees", attendees_show_path %>
<p>
Tickets
<p>

app/views/admins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Admins</h1>

<div id="admins">
  <% @admins.each do |admin| %>
    <%= render admin %>
    <p>
      <%= link_to "Show this admin", admin %>
    </p>
  <% end %>
</div>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/order_history.html.erb
<% if @order_histories&.any? %>
  <ul>
    <% @order_histories.each do |order| %>
      <p>
        <strong>Buyer Name:</strong>
        <%= @name  %>
      </p>
      <% if order.attendee.present? %>
        <p>
          <strong>Belongs to:</strong>
          <%= order.attendee.name %>
        </p>
        <p>
          <strong>Attendee id:</strong>
          <%= order.attendee.id %>
        </p>
      <% else %>
        <p>
          <strong>Belongs to:</strong>
          <%= order.admin.name %>
        </p>
        <p>
          <strong>Admin id:</strong>
          <%= order.admin.id %>
        </p>
      <% end %>

      <p>
        <strong>Event:</strong>
        <%= order.event.name %>
      </p>

      <p>
        <strong>Room:</strong>
        <%= order.room.address %>
      </p>

      <p>
        <strong>Confirmation number:</strong>
        <%= order.confirmation_number %>
      </p>
      <br>
    <% end %>
  </ul>
<% else %>
  <p>No orders found.</p>
<% end %>

app/views/admins/search_attendees.html.erb
<h1>Search Results for <%= @event_name %></h1>

<% if @event_tickets.any? %>
  <ul>
    <% @event_tickets.each do |event_ticket| %>
      <% if event_ticket.attendee.present? %>
        <% attendee = event_ticket.attendee %>
        <%= render attendee %>
        <p>
          <strong>Confirmation number</strong>
          <%= event_ticket.confirmation_number %>
        </p>
      <% end %>
      <% if event_ticket.admin.present? %>
        <% admin = event_ticket.admin %>
        <%= render admin %>
        <p>
          <strong>Confirmation number</strong>
          <%= event_ticket.confirmation_number %>
        </p>
      <% end %>
      <br/>
    <% end %>
  </ul>
<% else %>
  <p>No attendees found for this event.</p>
<% end %>

app/views/admins/show.html.erb
<style>
  .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
  }
  .header-container {
      display: flex;
      gap: 10px
  }
</style>

<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>
<div class="header">
  <h1>Welcome, <%= @admin.email %></h1>
  <div class="header-container">
    <%= link_to "Edit profile", edit_admin_path(@admin) %>
    <%= button_to "Log out", destroy_admin_session_path, method: :delete %>
  </div>
</div>
<br>

<div class = "attendee-link">
  <h2>Attendees</h2>
  <%= link_to "manage attendees", attendees_path %>
  <%= link_to "add new attendee", new_attendee_path %>
</div>

<div class = "room-link">
  <h2>Rooms</h2>
  <%= link_to "manage rooms", rooms_path %>
  <%= link_to "add new room", new_room_path %>
</div>

<div class = "event-link">
  <h2>Events</h2>
  <%= link_to "manage events", events_path %>
  <%= link_to "add new event", new_event_path %>
</div>

<!--Filter attendees by event, EXTRA CREDIT -->

<!-- This form allows the admin to select an event from a dropdown and
 search for all attendees that have booked tickets for that event.
 The form submits a GET request to the 'search_attendees_path'
 which is handled by the 'search_attendees' action in the AdminsController. -->
<p style="font-weight: bold;">View booked attendees by event:</p>

<%= form_with(url: search_attendees_path, method: :get) do |form| %>
  <%= form.label :event_name, 'Event Name:' %>
  <!-- Dropdown for selecting an event name.
  The options are dynamically generated from the @event_names instance variable
  which should be set in the AdminsController#show action. -->
  <%= form.select :event_name, options_for_select([['Select an event name', '']] + @event_names.map { |name| [name, name] }), {}, {class: "form-control"} %>
  <!-- Submission button for the form.
  When clicked, the selected event name is sent to the server
  to retrieve the corresponding attendees. -->
  <%= form.submit 'Search', class: "btn btn-primary" %>
<% end %>

<div class = "ticket-link">
  <h2>Tickets</h2>
  <%= link_to "manage tickets", event_tickets_path %>
  <%= link_to 'Order History', admin_order_history_path %>
  <%= link_to "book new ticket for attendee", new_event_ticket_path %>

</div>

<div class = "review-link">
  <h2>Reviews</h2>
  <%= link_to "manage reviews", reviews_path %>
<!--  Need to edit this so attendee can only make a review on behalf of themself.
      This is similar but opposite functionality issue to ticket booking/ creation
      on the admin side; right now you can only book a ticket for yourself,
      where as with reviews you can choose whomever to book a review for. -->
  <%= link_to "add new review", new_review_path %>
</div>