config/routes.rb
Rails.application.routes.draw do
  get 'login/index'
  devise_for :attendees
  devise_for :admins
  resources :reviews
  resources :event_tickets
  resources :events do
    get 'available_rooms', on: :collection
  end
  resources :rooms
  resources :attendees
  resources :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "login#index"

  get 'attendees/:id/view_booked_events' => 'attendees#booked_events', :as => :booked_events

  # Route for admin to search for attendees by event name. This maps a GET request to the search_attendees action in the AdminsController.
  get 'admin/search_attendees', to: 'admins#search_attendees', as: 'search_attendees'

  get 'admins/:id/order_history', to: 'admins#order_history', as: 'admin_order_history'
  get 'attendees/:id/order_history', to: 'attendees#order_history', as: 'attendee_order_history'

  # post 'events/available_rooms', to: 'events#available_rooms', as: 'available_rooms'

end

app/models/attendee.rb
class Attendee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :event_tickets, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :events, through: :event_tickets

  # Validations ensure all fields are filled upon edit / new action taken by user.
  validates :email, uniqueness: true, presence: true
  validates :name, presence: true
  validates :phone_number, presence: true, length: { is: 10 }
  validates :address, presence: true
  validates :credit_card_info, presence: true, length: { is: 16 }
end

app/controllers/attendees/confirmations_controller.rb
# frozen_string_literal: true

class Attendees::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/attendees/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Attendees::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/attendees/passwords_controller.rb
# frozen_string_literal: true

class Attendees::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/attendees/registrations_controller.rb
# frozen_string_literal: true

class Attendees::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/attendees/sessions_controller.rb
# frozen_string_literal: true

class Attendees::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/attendees/unlocks_controller.rb
# frozen_string_literal: true

class Attendees::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: %i[ show edit update destroy ]
  before_action :authorization_admin_only, only: [:index]
  before_action :only_allow_current_attendee, only: [:booked_events, :order_history, :edit]
  before_action :check_access, only: [:new]

  # GET /attendees or /attendees.json
  def index
    @attendees = Attendee.all
  end

  # GET /attendees/1 or /attendees/1.json
  def show
  end



  # GET /attendees/new
  def new
    @attendee = Attendee.new
  end

  # GET /attendees/1/edit
  def edit
  end

  # POST /attendees or /attendees.json
  def create
    @attendee = Attendee.new(attendee_params)

    respond_to do |format|
      if @attendee.save
        if admin_signed_in?
          format.html { redirect_to attendees_path, notice: "Attendee was successfully created." }
          format.json { render :show, status: :created, location: @attendee }
        else
          format.html { redirect_to attendee_url(@attendee), notice: "Attendee was successfully created." }
          format.json { render :show, status: :created, location: @attendee }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendees/1 or /attendees/1.json
  def update
    respond_to do |format|
      if @attendee.update(attendee_params)
        format.html { redirect_to attendee_url(@attendee), notice: "Attendee was successfully updated." }
        format.json { render :show, status: :ok, location: @attendee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1 or /attendees/1.json
  def destroy
    @attendee.destroy

    respond_to do |format|
      format.html { redirect_to attendees_url, notice: "Attendee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def booked_events
    @attendee = Attendee.find(params[:id])
    @events = @attendee.events
    @event_tickets = @attendee.event_tickets
  end

  def order_history
    @order_histories = EventTicket.where(buyer: current_attendee) || EventTicket.none
    @name = current_attendee.name
  end

  private

  def authorization_admin_only
    unless admin_signed_in?
      redirect_to root_path, alert: "Only admin can access this page."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

  def only_allow_current_attendee
    requested_attendee = Attendee.find(params[:id])
    unless current_attendee == requested_attendee
      redirect_to current_attendee, alert: "You are not authorized to view this page."
    end
  end

    # Only allow a list of trusted parameters through.
    def attendee_params
      params.require(:attendee).permit(:email, :name, :phone_number, :address, :credit_card_info)
    end

  # Define a method to check if the user is authorized to access the new action
  def check_access
    unless admin_or_unregistered?
      flash[:alert] = "You are not authorized to access this page."
      redirect_to root_path
    end
  end

  # Helper method to determine if the user is an admin or not registered
  def admin_or_unregistered?
    current_attendee.nil? || admin_signed_in?
  end
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/_attendee.html.erb
<div id="<%= dom_id attendee %>">
  <p>
    <strong>Email:</strong>
    <%= attendee.email %>
  </p>

<!--  <p>-->
<!--    <strong>Password:</strong>-->
    <%#= attendee.password %>
<!--  </p>-->

  <p>
    <strong>Name:</strong>
    <%= attendee.name %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= attendee.phone_number %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= attendee.address %>
  </p>

  <p>
    <strong>Credit card info:</strong>
    <%= attendee.credit_card_info %>
  </p>

</div>

app/views/attendees/_form.html.erb
<%= form_with(model: attendee) do |form| %>
  <% if attendee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
        <% attendee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

<!--   Todo: Maybe remove this since it has no impact-->
  <% unless attendee_signed_in? %>
    <div>
      <%= form.label :password, style: "display: block" %>
      <%= form.text_field :password %>
    </div>
  <% end %>


  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_area :address %>
  </div>

  <div>
    <%= form.label :credit_card_info, style: "display: block" %>
    <%= form.text_field :credit_card_info %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/attendees/booked_events.html.erb
<h1>Your booked events</h1>

<div id="booked_events">
  <% @event_tickets.each do |event_ticket| %>
    <% if event_ticket.buyer_type == 'Attendee' %>
      <p>
        <strong>Buyer name:</strong>
        <%= Attendee.find(event_ticket.buyer_id).name %>
      </p>
    <% else %>
      <p>
        <strong>Buyer name:</strong>
        <%= Admin.find(event_ticket.buyer_id).name %>
      </p>
    <% end %>
    <p>
      <strong>Event name: </strong>
      <%= event_ticket.event.name %>
    </p>
    <p>
      <strong>Event Date</strong>
      <%= event_ticket.event.date %>
    </p>
    <p>
      <strong>Start time:</strong>
      <%= event_ticket.event.start_time.strftime("%H:%M") %>
    </p>

    <p>
      <strong>End time:</strong>
      <%= event_ticket.event.end_time.strftime("%H:%M") %>
    </p>

    <p>
      <%= link_to 'View ticket', event_ticket_path(event_ticket), method: :get %>
    </p>
    <br>
  <% end %>
</div>

app/views/attendees/edit.html.erb
<h1>Editing attendee</h1>

<%= render "form", attendee: @attendee %>

<br>

<% if admin_signed_in? %>
  <div>
    <%= link_to "Show this attendee", @attendee %> |
    <%= link_to "Back to attendees", attendees_path %>
  </div>
<% end %>


<% if attendee_signed_in? %>
  <div>
    <%= link_to "back to main page", @attendee %> |
  </div>
<% end %>

app/views/attendees/home.html.erb
<h1>Attendee Homepage</h1>
<p>See attendee options below.</p>

app/views/attendees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Attendees</h1>

<div id="attendees">
  <% @attendees.each do |attendee| %>
    <%= render attendee %>
    <p>
      <%= link_to "Show this attendee", attendee %>
    </p>
  <% end %>
</div>

<!--Dont think we need this since the create attendee should be just "sign up"-->
<%#= link_to "New attendee", new_attendee_path %>

app/views/attendees/new.html.erb
<h1>New attendee</h1>

<%= render "form", attendee: @attendee %>

<br>

<div>
  <%= link_to "Back to attendees", attendees_path %>
</div>

app/views/attendees/order_history.html.erb
<% if @order_histories&.any? %>
  <ul>
    <% @order_histories.each do |order| %>
      <p>
        <strong>Buyer Name:</strong>
        <%= @name  %>
      </p>
      <% if order.attendee.present? %>
        <p>
          <strong>Belongs to:</strong>
          <%= order.attendee.name %>
        </p>
        <p>
          <strong>Attendee id:</strong>
          <%= order.attendee.id %>
        </p>
      <% else %>
        <p>
          <strong>Belongs to:</strong>
          <%= order.admin.name %>
        </p>
        <p>
          <strong>Admin id:</strong>
          <%= order.admin.id %>
        </p>
      <% end %>

      <p>
        <strong>Event:</strong>
        <%= order.event.name %>
      </p>

      <p>
        <strong>Room:</strong>
        <%= order.room.address %>
      </p>

      <p>
        <strong>Confirmation number:</strong>
        <%= order.confirmation_number %>
      </p>
      <br>
    <% end %>
  </ul>
<% else %>
  <p>No orders found.</p>
<% end %>

app/views/attendees/show.html.erb
<style>
    .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    .header-container {
        display: flex;
        gap: 10px
    }
</style>

<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<div class="header">
  <h1><%= @attendee.email %></h1>

  <% if admin_signed_in? %>
    <%= render @attendee %>>
  <% end %>

  <div class="header-container">
    <%= link_to "Edit profile", edit_attendee_path(@attendee) %>
    <%= link_to "change password", edit_attendee_registration_path %>
    <% if attendee_signed_in? %>
      <%= button_to "Log out", destroy_attendee_session_path, method: :delete %>
      <%= button_to "delete your account", @attendee, method: :delete %>
    <% end %>

    <% if admin_signed_in? %>
      <%= button_to "Destroy this attendee", @attendee, method: :delete %>
    <% end %>

  </div>
</div>

<br>


<div>
  <% if admin_signed_in? %>
    <%= link_to "Back to attendees", attendees_path %>
  <% end %>
</div>
<div class = "event-link">
  <% if attendee_signed_in? %>
    <h2>Events</h2>
    <%= link_to "view events", events_path %>
    <h2>Tickets</h2>
    <%= link_to "Booked events", booked_events_path(@attendee) %>
    <%= link_to 'Order History', attendee_order_history_path %>
    <%= link_to "Buy tickets for others", new_event_ticket_path %>
    <h2>Reviews</h2>
    <%= link_to "manage reviews", reviews_path %>
    <!--  Need to edit this so attendee can only MAKE AND MANAGE a review on behalf of themself.
      This is similar but opposite functionality issue to ticket booking/ creation
      on the admin side; right now you can only book a ticket for yourself,
      where as with reviews you can choose whomever to book a review for. -->
    <%= link_to "add new review", new_review_path %>
    </div>
  <% end %>
</div>