config/routes.rb
Rails.application.routes.draw do
  get 'login/index'
  devise_for :attendees
  devise_for :admins
  resources :reviews
  resources :event_tickets
  resources :events do
    get 'available_rooms', on: :collection
  end
  resources :rooms
  resources :attendees
  resources :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "login#index"

  get 'attendees/:id/view_booked_events' => 'attendees#booked_events', :as => :booked_events

  # Route for admin to search for attendees by event name. This maps a GET request to the search_attendees action in the AdminsController.
  get 'admin/search_attendees', to: 'admins#search_attendees', as: 'search_attendees'

  get 'admins/:id/order_history', to: 'admins#order_history', as: 'admin_order_history'
  get 'attendees/:id/order_history', to: 'attendees#order_history', as: 'attendee_order_history'

  # post 'events/available_rooms', to: 'events#available_rooms', as: 'available_rooms'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WolfEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if admin_signed_in? %>
    <div>
      <%= link_to "main page", current_admin %>
    </div>
  <% end %>
  <% if attendee_signed_in? %>
    <div>
      <%= link_to "main page", current_attendee %>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>